# Generated by Django 4.2.17 on 2024-12-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Bid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('author', models.TextField(default='anonymous')),
                ('genre', models.TextField(default='unknown', null=True)),
                ('fine', models.PositiveSmallIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('days', models.PositiveIntegerField(default=0)),
                ('submit', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('issued_bid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
