# Generated by Django 4.2.17 on 2024-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_books_id_alter_books_bid_alter_issued_issued_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
