# Generated by Django 4.2.17 on 2024-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_books_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available_quantity',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]
