# Generated by Django 4.2.17 on 2024-12-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_books_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issued',
            name='issued_bid',
        ),
        migrations.AddField(
            model_name='issued',
            name='Issue_No',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
