# Generated by Django 4.2.17 on 2024-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_issued_issued_bid_issued_issue_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='Issue_No',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
