# Generated by Django 4.2.17 on 2024-12-17 17:21

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_issued_issue_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='Issue_No',
            field=models.CharField(default=Home.models.get_next_issue_no, max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
