# Generated by Django 4.2.17 on 2024-12-18 08:13

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_issued_issue_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Bid',
            field=models.IntegerField(default=Home.models.get_next_bid, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issued',
            name='Issue_No',
            field=models.IntegerField(default=Home.models.get_next_issue_no, primary_key=True, serialize=False, unique=True),
        ),
    ]
