# Generated by Django 4.2.17 on 2024-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_books_id_alter_books_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
